/**
 * `npm run deploy:render` / `npm run deploy:check`.
 *
 * Renders the topology into two committed artifacts:
 *
 *  - `deploy/generated/topology.json` — what every Cloud Run service, queue,
 *    schedule and job must look like, in one machine-readable file;
 *  - `deploy/generated/promotion-plan.md` — the exact ordered commands that
 *    promote the lean service digest and the CPU-model analysis digest, so a
 *    release is a transcript rather than remembered flags.
 *
 * `--check` re-renders and diffs instead of writing, so a topology change that
 * was never rendered fails CI rather than leaving the committed plan lying.
 * The generator is the only writer: hand-editing these files is a drift finding.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import {
  DEPLOYMENTS,
  JOBS,
  QUEUE_ROUTES,
  SCHEDULES,
  inspectTopology,
  peakConnections,
} from "../topology.js";
import { urlEnvFor } from "../deployment.js";

const REGION = process.env.FORMA_REGION ?? "europe-west1";
const PROJECT = process.env.FORMA_GCP_PROJECT ?? "tempo-chess-neri";

/** Repository root, from `server/`. */
const ROOT = join(process.cwd(), "..");
const OUT_DIR = join(ROOT, "deploy", "generated");

function serviceAccountEmail(id: string): string {
  return `${id}@${PROJECT}.iam.gserviceaccount.com`;
}

function renderTopologyJson(): string {
  const document = {
    $comment:
      "Generated by npm run deploy:render from server/src/platform/topology.ts. Do not edit.",
    project: PROJECT,
    region: REGION,
    connectionBudget: {
      availableToServices: DEPLOYMENTS.reduce((total, entry) => total + peakConnections(entry), 0),
    },
    services: DEPLOYMENTS.map((entry) => ({
      name: entry.name,
      ingress: entry.ingress === "public" ? "all" : "internal",
      allowUnauthenticated: entry.ingress === "public",
      serviceAccount: serviceAccountEmail(entry.serviceAccount),
      databaseRole: entry.databaseRole,
      databaseSecret: entry.databaseSecret,
      audience: entry.audience,
      urlEnv: urlEnvFor(entry.name),
      capabilities: [...entry.capabilities],
      executes: [...entry.executes],
      maxInstances: entry.maxInstances,
      containerConcurrency: entry.containerConcurrency,
      poolSize: entry.poolSize,
      peakConnections: peakConnections(entry),
      cpu: entry.cpu,
      memory: entry.memory,
      timeoutSeconds: entry.timeoutSeconds,
    })),
    queues: QUEUE_ROUTES.map((entry) => ({
      name: entry.name,
      target: entry.target,
      maxConcurrentDispatches: entry.maxConcurrentDispatches,
      maxDispatchesPerSecond: entry.maxDispatchesPerSecond,
      maxAttempts: entry.maxAttempts,
    })),
    schedules: SCHEDULES.map((entry) => ({
      name: entry.name,
      target: entry.target,
      path: entry.path,
      schedule: entry.schedule,
      purpose: entry.purpose,
      oidcServiceAccount: serviceAccountEmail("forma-scheduler"),
    })),
    jobs: JOBS.map((entry) => ({
      name: entry.name,
      serviceAccount: serviceAccountEmail(entry.serviceAccount),
      databaseRole: entry.databaseRole,
      command: entry.command,
      purpose: entry.purpose,
      maxRetries: entry.maxRetries,
      timeoutSeconds: entry.timeoutSeconds,
    })),
  };
  return `${JSON.stringify(document, null, 2)}\n`;
}

function renderPromotionPlan(): string {
  const lines: string[] = [];
  lines.push("# Promotion plan");
  lines.push("");
  lines.push(
    "Generated by `npm run deploy:render`. Do not edit; change `server/src/platform/topology.ts`.",
  );
  lines.push("");
  lines.push("Two image digests are built once and promoted: the lean service image and");
  lines.push("the CPU-only Maia serving target. Every command below names a digest, so");
  lines.push("what is smoke-tested is byte-identical to what serves traffic.");
  lines.push("");
  lines.push("## 1. Build the two digests");
  lines.push("");
  lines.push("```bash");
  lines.push(`gcloud builds submit --project ${PROJECT} --region ${REGION} \\`);
  lines.push(
    `  --tag ${REGION}-docker.pkg.dev/${PROJECT}/cloud-run-source-deploy/forma:$(git rev-parse --short HEAD)`,
  );
  lines.push("");
  lines.push(`gcloud builds submit --project ${PROJECT} --region ${REGION} \\`);
  lines.push("  --config cloudbuild.maia3.yaml \\");
  lines.push(
    `  --substitutions=_IMAGE=${REGION}-docker.pkg.dev/${PROJECT}/cloud-run-source-deploy/forma-maia:$(git rev-parse --short HEAD)`,
  );
  lines.push("```");
  lines.push("");
  lines.push("Record the resulting digests as `BASE_DIGEST` and `MAIA_DIGEST`.");
  lines.push("Nothing below builds again.");
  lines.push("");
  lines.push("## 2. Stage the digest with no traffic");
  lines.push("");
  lines.push(
    "Decision D2: staging is a tagged revision of the same service, not a second",
  );
  lines.push(
    "project. `--no-traffic --tag=next` gives a reachable URL that serves nobody.",
  );
  lines.push("");
  lines.push("```bash");
  for (const entry of DEPLOYMENTS) {
    lines.push(`gcloud run deploy ${entry.name} --project ${PROJECT} --region ${REGION} \\`);
    lines.push(
      `  --image ${entry.name === "forma-maia" ? "$MAIA_DIGEST" : "$BASE_DIGEST"} --no-traffic --tag=next \\`,
    );
    lines.push(`  --service-account ${serviceAccountEmail(entry.serviceAccount)} \\`);
    lines.push(
      `  --ingress ${entry.ingress === "public" ? "all" : "internal"} ` +
        `${entry.ingress === "public" ? "--allow-unauthenticated" : "--no-allow-unauthenticated"} \\`,
    );
    lines.push(
      `  --max-instances ${entry.maxInstances} --concurrency ${entry.containerConcurrency} \\`,
    );
    lines.push(`  --cpu ${entry.cpu} --memory ${entry.memory} --timeout ${entry.timeoutSeconds} \\`);
    lines.push(`  --set-secrets DATABASE_URL=${entry.databaseSecret}:latest \\`);
    lines.push(`  --set-env-vars FORMA_DEPLOYMENT=${entry.name},DATABASE_ROLE=${entry.databaseRole}`);
    lines.push("");
  }
  lines.push("```");
  lines.push("");
  lines.push("## 3. Smoke the staged revision");
  lines.push("");
  lines.push("```bash");
  lines.push("curl -fsS \"$(gcloud run services describe forma-api --project " + PROJECT);
  lines.push(
    `  --region ${REGION} --format='value(status.traffic.filter(tag:next).url)')/health\"`,
  );
  lines.push("```");
  lines.push("");
  lines.push(
    "Private services are not curled from a laptop by design; their smoke is the",
  );
  lines.push("scheduler's next authenticated invocation and the queue drain below.");
  lines.push("");
  lines.push("## 4. Promote");
  lines.push("");
  lines.push("```bash");
  for (const entry of DEPLOYMENTS) {
    lines.push(
      `gcloud run services update-traffic ${entry.name} --project ${PROJECT} ` +
        `--region ${REGION} --to-tags next=100`,
    );
  }
  lines.push("```");
  lines.push("");
  lines.push("## 5. Rollback");
  lines.push("");
  lines.push(
    "The previous revision is still there and still healthy; rollback is traffic,",
  );
  lines.push("not a rebuild.");
  lines.push("");
  lines.push("```bash");
  lines.push(
    `gcloud run services update-traffic <service> --project ${PROJECT} ` +
      `--region ${REGION} --to-revisions <previous>=100`,
  );
  lines.push("```");
  lines.push("");
  lines.push("## Queues, schedules and jobs");
  lines.push("");
  lines.push("| Queue | Target | Max concurrent | Attempts |");
  lines.push("| --- | --- | --- | --- |");
  for (const entry of QUEUE_ROUTES) {
    lines.push(
      `| \`${entry.name}\` | ${entry.target} | ${entry.maxConcurrentDispatches} | ${entry.maxAttempts} |`,
    );
  }
  lines.push("");
  lines.push("| Schedule | Target | Cron | Purpose |");
  lines.push("| --- | --- | --- | --- |");
  for (const entry of SCHEDULES) {
    lines.push(`| \`${entry.name}\` | ${entry.target} | \`${entry.schedule}\` | ${entry.purpose} |`);
  }
  lines.push("");
  lines.push("| Job | Runs as | Command | Purpose |");
  lines.push("| --- | --- | --- | --- |");
  for (const entry of JOBS) {
    lines.push(
      `| \`${entry.name}\` | ${entry.databaseRole} | \`${entry.command}\` | ${entry.purpose} |`,
    );
  }
  lines.push("");
  return `${lines.join("\n")}`;
}

const ARTIFACTS: readonly { path: string; render: () => string }[] = [
  { path: join(OUT_DIR, "topology.json"), render: renderTopologyJson },
  { path: join(OUT_DIR, "promotion-plan.md"), render: renderPromotionPlan },
];

const findings = inspectTopology();
if (findings.length > 0) {
  console.error("the topology contradicts itself; refusing to render:");
  for (const finding of findings) console.error(`  - ${finding}`);
  process.exit(1);
}

const checking = process.argv.includes("--check");
let drifted = 0;

for (const artifact of ARTIFACTS) {
  const rendered = artifact.render();
  if (checking) {
    let committed = "";
    try {
      committed = readFileSync(artifact.path, "utf8");
    } catch {
      committed = "";
    }
    if (committed !== rendered) {
      drifted += 1;
      console.error(`drift: ${artifact.path} is not what the topology renders`);
    } else {
      console.log(`ok   ${artifact.path}`);
    }
    continue;
  }
  mkdirSync(dirname(artifact.path), { recursive: true });
  writeFileSync(artifact.path, rendered, "utf8");
  console.log(`wrote ${artifact.path}`);
}

if (checking) {
  if (drifted > 0) {
    console.error(`\n${drifted} generated artifact(s) drifted; run npm run deploy:render`);
    process.exitCode = 1;
  } else {
    console.log(`\n${ARTIFACTS.length} generated artifacts match the topology`);
  }
}
